config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"
  devise_for :users

  resources :leagues, only: [:show, :new, :create]
  
end

app/models/league.rb
class League < ActiveRecord::Base
	has_many :user_leagues, dependent: :destroy
	has_many :users, through: :user_leagues

	has_many :temp_user_leagues, dependent: :destroy
	has_many :temp_users, through: :temp_user_leagues
end

app/models/temp_user.rb
class TempUser < ActiveRecord::Base
	has_many :temp_user_leagues, dependent: :destroy
	has_many :leagues, through: :temp_user_leagues
end

app/models/temp_user_league.rb
class TempUserLeague < ActiveRecord::Base
	belongs_to :temp_user
	belongs_to :league
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :user_leagues, dependent: :destroy
  has_many :leagues, through: :user_leagues

end

app/models/user_league.rb
class UserLeague < ActiveRecord::Base
	belongs_to :user
	belongs_to :league
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def after_sign_in_path
  	root_path
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

	def index
		redirect_to new_user_session_path if !user_signed_in?
	end

end

app/controllers/leagues_controller.rb
class LeaguesController < ApplicationController
	before_action :authenticate_user!

	def new
		@league = League.new
	end

	def create
		@league = League.new(league_params)

		if @league.save!
			email_order = randomize_email_order(params[:email])
			params[:email].each do |email|
				user = User.find_by(email: email)
				if user
					user.leagues << @league
				else
					temp = TempUser.find_or_create_by(email: email)
					temp.leagues << @league
				end
				user = user || temp
				UserNotifier.draft_order_email(current_user, @league, user, email_order).deliver
			end
		else
			render 'new'
		end
		redirect_to root_path
	end

	private

	def randomize_email_order(emails)
		email_order = {}
		emails.shuffle!

		emails.each_with_index do |email, index|
			email_order[index+1] = email
		end

		email_order
	end

	def league_params
		params.require(:league).permit(:name)
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :authenticate_user!
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<div class="row" style="margin-top:20px;">
	<div class="col-md-10 col-md-offset-1">
		<%= link_to new_league_path do %>
			<button class="btn btn-block btn-success">
				<%= fa_icon "plus" %> Create New League
			</button>
		<% end %>
		<% if current_user.leagues.any? %>
			<h3>My Leagues:</h3>
				<ul>
					<% current_user.leagues.each do |league| %>
						<li><%= league.name %></li>
					<% end %>
				</ul>
		<% else %>
			<h3 class="text-center">You don't have any leagues yet.</h3>
		<% end %>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Randomfantasy</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
	<%= render partial: 'shared/nav' if user_signed_in? %>
	<div class="container">
		
		<%= yield %>
	</div>

</body>
</html>

app/views/leagues/_email_form.html.erb
<%= email_field_tag 'email[]', '', class: 'form-control', style: 'margin-bottom:5px;', required: true %>

app/views/leagues/new.html.erb
<div class="row" style="margin-top:20px;">
	<div class="col-md-6 col-md-offset-3">
		<%= simple_form_for @league do |f| %>
			<%= f.input :name, label: "Name of League", required: true %>
			<label class="string required control-label">Participants</label>
			<div class="emailForm">
				<%= render partial: 'email_form' %>
			</div>
			<a href="javascript:;" id="addNewEmail"><%= fa_icon "plus" %> Add Another Email</a>
			&nbsp;
			<a href="javascript:;" id="removeEmail"><%= fa_icon "minus" %> Remove Last Email</a>
			<%= f.button :submit, class: "btn btn-block btn-success", style: "margin-top:10px;" %>
		<% end %>
	</div>
</div>

<div class="hidden" id="new_email_form">
  <%= render partial: "email_form" %>
</div>

<script>
$(document).ready(function(){
  $("#addNewEmail").click(function(){
    $(".emailForm").append($("#new_email_form").html());
  });

  $("#removeEmail").click(function(){
    $(".emailForm").children().last().remove();
  });
});
</script>

app/views/shared/_nav.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'RandomFantasy', root_path, class: 'navbar-brand' %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li>
	        <%= link_to 'Logout', destroy_user_session_path, method: :delete %>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/user_notifier/draft_order_email.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta content='text/html; charset=UTF-8' http-equiv='Content-Type' />
  </head>
  <body>
    <h3>Draft Order for <%= @league.name %>:</h3>
    <% @draft_order.each do |order, email| %>
	    <p><%= order %>. <%= email %></p>
    <% end %>
    <br />
    <br />
    <p>Randomized by <%= @league_owner.email %></p>
  </body>
  <hr />
</html>